import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'

import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={ cn("bg-secondary", inter.className)}> 
        {/* ye upar cn vala part optional hai can remove it if bg aacha nahi hia to  */}
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <Toaster/>
          </ThemeProvider>
          <ModeToggle/>
          </body>
      </html>
    </ClerkProvider>

  );
}
